### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by WhiteBlackGoose** [WhiteBlackGoose/andromeda.nvim#1]
- [x] Folded should be lighter than bg, not darker
- [x] Deleted lines DiffDelete
- [x] Cursor line to be less aggressive
- [ ] Border between tabs
